steps:

- bash: |
   if [[ $(build.sourceBranchName) =~ develop|master ]]; 
   then 
   echo "##vso[task.setvariable variable=ServiceVersion]1.$(build.buildNumber)"
   fi
   
  displayName: 'Bash Script'



- bash: 'echo "Service Version $SERVICEVERSION"' 

  displayName: 'Display variables'



