queue:

  name: Hosted VS2017

steps:

- bash: |
   if [[ $(build.sourceBranchName) =~ develop|master ]]; 
   then 
   echo "##vso[task.setvariable variable=ServiceVersion]1.$(build.buildNumber)"
   fi
   
   echo "No problem reading $SAUCE" 

  displayName: 'Bash Script'

- bash: 'echo "Service Version $SERVICEVERSION"' 

  displayName: 'Display variables'



