steps:

- bash: |
   if [[ $(build.sourceBranchName) =~ develop|master ]]; 
   then 
   echo "##vso[task.setvariable variable=ServiceVersion]1.$(build.buildNumber)"
   else
   echo "##vso[task.setvariable variable=ServiceVersion]0.$(build.buildNumber)"
   fi

  displayName: 'Bash Script'


- bash: 'echo "Service Version $SERVICEVERSION"' 

        echo "##vso[build.updatebuildnumber]$SERVICEVERSION"

 displayName: 'Display variables'



