steps:
ktuikdj

fytuyt
yuifyu'tdhsr''
drtyhdr
- bash: |
   if [[ $(build.sourceBranchName) =~ develop|master ]]; 
   then 
   echo "##vso[task.setvariable variable=ServiceVersion]1.$(build.buildNumber)"
   else
   echo "##vso[task.setvariable variable=ServiceVersion]0.$(build.buildNumber)"
   fi

  displayName: 'Bash Script'


- bash: 'echo "Service Version $SERVICEVERSION"' 

  displayName: 'Display variables'

- bash: echo "##vso[build.updatebuildnumber]$SERVICEVERSION"

  displayName: 'resetnumber'
 

dfsdag
dhsrht
io;
